name: modul_2_chart
description: Modul 2 praktikum mata kuliah PPBL
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.2
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data_sensor.csv
    - assets/soil_hum.json
